name: Deploy Discord Bot

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

            - name: SSH into Raspberry Pi and update bot
              run: |
                  ssh pi@192.168.1.35 'cd elmo-discord-bot && git pull && npm i && pm2 restart deploy-commands.js'
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
