name: Deploy Discord Bot On Raspberry Pi

on:
    push:
        branches:
            - main
    workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Packages
              run: npm i

            - name: Build & Run
              run: node deploy-commands.js
